### ISSUE TITLE
[user-managment] Support specifying multiple groups

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-deploy#157]
Right now, we have 3 group types (admin, sudo, users), but for each of these, we can only specify a single LDAP group mapped to it.

We need to be able to feed something like a "," separated list of groups, something like:

```
global_admins = "nubis_global_admins,moco_admins"
sudo_users    = "nubis_sudo_users,posix_sysadmins"
users         = "nubis_users, bugzilla_devops"
```

**Comment by limed** [comment]
Fixed in #171
