### ISSUE TITLE
Open up ports for monitoring security groups

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-deploy#416]
For kubernetes to be monitored we need these ports opened

8080 - API server (master only)
10251 - kube-scheduler (master only)
10252 - kube-controller-manager (master only)
10255 - Read-Only Kubelet API (master and node)

**Comment by gozer** [comment]
But that’s something that belongs in nubis-Kubernetes itself.

It can grant ingress access to the monitoring sg to these ports itself.

**Comment by limed** [comment]
Moved to nubisproject/nubis-kubernetes#36
