### ISSUE TITLE
[dns] Create an <account-id>.<nubis.allizom.org> zone

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-deploy#443]
To give us a pubicly accessible mechanism to map account-id to the account itself....

**Comment by gene1wood** [comment]
gozer writes in nubisproject/nubis-deploy#439

> Just so you know, I've thought about my suggestion and reviewed the context I was missing, and turns out my idea wasn't actually simple or practical in terms of implementation...

as to why this is closed
