### ISSUE TITLE
[nat] Bump up instance type

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-deploy#67]
Currently using t2.nano which causes bro to be a little unhappy so we should bump it up to m3.mediums

**Comment by limed** [comment]
Tested with t2.small and seems to be doing fine so suggest using t2.small

**Comment by RichardWeiss** [comment]
t2.small may work fine, but we should keep an eye on it. The t2 family uses [CPU credits](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html#t2-instances-cpu-credits). When you run out of credits, CPU performance drops to a small percentage of a whole core.
